-- MySQL Script generated by MySQL Workbench
-- Fri Jun  4 19:28:30 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema taxi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema taxi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taxi_rework` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `taxi_rework` ;

-- -----------------------------------------------------
-- Table `taxi_rework`.`car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taxi_rework`.`car` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lic_plate` VARCHAR(32) NULL DEFAULT NULL,
  `name` VARCHAR(32) NULL DEFAULT NULL,
  `class` ENUM('ECONOM', 'ECONOMXL', 'COMFORT', 'VAN', 'BUSINESS', 'ELITE') NULL DEFAULT NULL,
  `status` ENUM('ACTIVE', 'BOOKED', 'INACTIVE') NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `lic_plate` (`lic_plate` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `taxi_rework`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taxi_rework`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(32) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `role` ENUM('ADMIN', 'CLIENT') NOT NULL DEFAULT 'CLIENT',
  `salt` BLOB NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 81
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `taxi_rework`.`ride`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taxi_rework`.`ride` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pos_from` VARCHAR(128) NOT NULL,
  `pos_to` VARCHAR(128) NOT NULL,
  `price` INT NOT NULL,
  `creation_time` DATETIME NOT NULL,
  `car_id` INT NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `car_id_idx` (`car_id` ASC) VISIBLE,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `car_id`
    FOREIGN KEY (`car_id`)
    REFERENCES `taxi_rework`.`car` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `taxi_rework`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 119
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `taxi_rework`.`user_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taxi_rework`.`user_info` (
  `user_id` INT NOT NULL,
  `first` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `last` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `total_spent` INT NOT NULL DEFAULT '0',
  INDEX `id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `taxi_rework`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

USE `taxi_rework`;

DELIMITER $$
USE `taxi_rework`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `taxi_rework`.`new_user_info_sum`
AFTER INSERT ON `taxi_rework`.`ride`
FOR EACH ROW
UPDATE user_info
     SET total_spent = (SELECT SUM(price) FROM ride WHERE user_id = NEW.user_id)
   WHERE user_id = NEW.user_id$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
